### ISSUE TITLE
Implement Tests

### ISSUE THREAD

**Issue by RafaelGoulartB** [RafaelGoulartB/blog-cms#29]
## Description
Implement tests with Jest.

## Tasks
- [ ] implement test at search results.
- [ ] implement test at index page
- [ ] implement test at articles page
